name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v2 
     with:
       fetch-depth: 0
   - name: Setup python # it seems that restore timestamps needs Python 2
     uses: actions/setup-python@v2
     with:
       python-version: "2.x"
   - name: restore timestamps
     uses: chetan/git-restore-mtime-action@release
   - name: Checkout siterebuild
     uses: actions/checkout@v2
     with:
      repository:  michal-h21/siterebuild 
      path: siterebuild
   - name: Run make4ht 
     uses: docker://ghcr.io/michal-h21/make4ht-action:latest 
     env: # we must go to the directory with tex posts and execute siterebuild
       command: "cd texposts && ../siterebuild/siterebuild -l debug && ls -lt blogging-in-latex-2021-edition && ls -lt ../docs/_posts/" 
